name: i18n_lightweight
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/Tobi696/i18n_lightweight

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  yaml: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
flutter:
